this is a todo-app repo

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -54,13 +54,14 @@ jobs:
           path: .
       - name: Verify Artifact Download
         run: |
-           ls -al
-          if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
-           echo "Artifact found"
-          else
-           echo "Artifact not found"
-           exit 1
-          fi
+          ls -al
+         if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
+          echo "Artifact found"
+         else
+          echo "Artifact not found"
+         exit 1
+         fi
+
 
       - name: Load Docker Image
         run: |
