this is a todo-app repo

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -40,70 +40,59 @@ jobs:
       app_version: ${{ steps.version.outputs.app_version }}
 
   Deploy:
-  name: Deploy Docker Image
-  runs-on: self-hosted
-  needs: Build
-  env:
-    username: dapper01
-    image_name: test-image
-  steps:
-    - name: Download Docker Image Artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: docker-image
-        path: .
+    name: Deploy Docker Image
+    runs-on: self-hosted
+    needs: Build
+    env:
+      username: dapper01
+      image_name: test-image
+    steps:
+      - name: Download Docker Image Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-image
+          path: .
 
-    - name: Verify Artifact Download
-      run: |
-        ls -al
-        if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
-          echo "Artifact found"
-        else
-          echo "Artifact not found"
-          exit 1
-        fi
+      - name: Verify Artifact Download
+        run: |
+          ls -al
+          if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
+            echo "Artifact found"
+          else
+            echo "Artifact not found"
+            exit 1
+          fi
 
-    - name: Load Docker Image
-      run: |
-        docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
+      - name: Load Docker Image
+        run: |
+          docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
 
-    - name: Verify Loaded Docker Image
-      run: |
-        docker images
+      - name: Verify Loaded Docker Image
+        run: |
+          docker images
 
-    - name: Debug: Print Image Details
-      run: |
-        echo "username: $username"
-        echo "image_name: $image_name"
-        echo "app_version: ${{ needs.Build.outputs.app_version }}
+      - name: Print Image Details
+        run: |
+          echo "username: $username"
+          echo "image_name: $image_name"
+          echo "app_version: ${{ needs.Build.outputs.app_version }}"
 
-    - name: Stop Containers Using Port 8081 (if any)
-      run: |
-        # Check for any container using port 8081 and stop it
-        CONTAINER_ID=$(docker ps --filter "publish=8081" -q)
-        if [ -n "$CONTAINER_ID" ]; then
-          echo "Stopping container $CONTAINER_ID"
-          docker stop $CONTAINER_ID
-        else
-          echo "No container found using port 8081"
-        fi
-
-    - name: Run Docker Containers
-      run: |
-        echo "Running container with image: $username/$image_name:${{ needs.Build.outputs.app_version }}"
-        docker run -d -p 8081:80 $username/$image_name:${{ needs.Build.outputs.app_version }}
-
-    - name: Send email notification
-      uses: dawidd6/action-send-mail@v3
-      with:
-        server_address: smtp.gmail.com
-        server_port: 465
-        secure: true
-        username: oladapper@gmail.com
-        password: ${{ secrets.EMAIL_PASSWORD }}
-        subject: "Docker Image Deployed from Artifact"
-        to: "oladapolawal12@yahoo.com"
-        from: "Mr David Agba DevOps"
-        body: |
-          Hello,
-          The latest version of the Docker image (version: ${{ needs.Build.outputs.app_version }}) has been deployed from the artifact.
+      - name: Run Docker Containers
+        run: |
+         echo "Running container with image: $username/$image_name:${{ needs.Build.outputs.app_version }}"
+         docker run -d -p 8082:80 $username/$image_name:${{ needs.Build.outputs.app_version }}
+        
+      - name: Send email notification
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 465
+          secure: true
+          username: oladapper@gmail.com
+          password: ${{ secrets.EMAIL_PASSWORD }}
+          subject: "Docker Image Deployed from Artifact"
+          to: "oladapolawal12@yahoo.com"
+          from: "Mr David Agba DevOps"
+          body: |
+            Hello,
+            The latest version of the Docker image (version: ${{ needs.Build.outputs.app_version }}) has been deployed from the artifact.
