this is a todo-app

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -42,7 +42,7 @@ jobs:
   Deploy:
     name: Deploy Docker Image
     runs-on: self-hosted
-    needs: Build  
+    needs: Build
     steps:
       - name: Download Docker Image Artifact
         uses: actions/download-artifact@v4
@@ -54,17 +54,17 @@ jobs:
         run: |
           ls -al
           if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
-            echo "Artifact found"
+           echo "Artifact found"
           else
-            echo "Artifact not found"
-            exit 1
-          fi
+           echo "Artifact not found"
+           exit 1
+        fi
 
       - name: Load Docker Image
         run: |
-          docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
+         docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
 
-      - name: Verify Loaded Docker Image
+       - name: Verify Loaded Docker Image
         run: |
           docker images  # Ensure the image is loaded successfully
 
@@ -75,14 +75,14 @@ jobs:
       - name: Send email notification
         uses: dawidd6/action-send-mail@v3
         with:
-          server_address: smtp.gmail.com
-          server_port: 465
-          secure: true
-          username: oladapper@gmail.com
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: "Docker Image Deployed from Artifact"
-          to: "oladapolawal12@yahoo.com"
-          from: "Mr David Agba DevOps"
-          body: |
-            Hello,
-            The latest version of the Docker image (version: ${{ needs.Build.outputs.app_version }}) has been deployed from the artifact.
+        server_address: smtp.gmail.com
+        server_port: 465
+        secure: true
+        username: oladapper@gmail.com
+        password: ${{ secrets.EMAIL_PASSWORD }}
+        subject: "Docker Image Deployed from Artifact"
+        to: "oladapolawal12@yahoo.com"
+        from: "Mr David Agba DevOps"
+        body: |
+          Hello,
+          The latest version of the Docker image (version: ${{ needs.Build.outputs.app_version }}) has been deployed from the artifact.
