this is a todo-app repo

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -40,50 +40,49 @@ jobs:
       app_version: ${{ steps.version.outputs.app_version }}
 
   Deploy:
-  name: Deploy Docker Image
-  runs-on: self-hosted
-  needs: Build
-  steps:
-    - name: Download Docker Image Artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: docker-image
-        path: .
+    name: Deploy Docker Image
+    runs-on: self-hosted
+    needs: Build
+    steps:
+      - name: Download Docker Image Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-image
+          path: .
 
-    - name: Verify Artifact Download
-      run: |
-        ls -al
-        if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
-          echo "Artifact found"
+      - name: Verify Artifact Download
+        run: |
+          ls -al
+          if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
+           echo "Artifact found"
         else
-          echo "Artifact not found"
-          exit 1
-        fi
+           echo "Artifact not found"
+           exit 1
+         fi
 
-    - name: Load Docker Image
-      run: |
-        docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
+      - name: Load Docker Image
+          run: |
+            docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
 
-    - name: Verify Loaded Docker Image
+      - name: Verify Loaded Docker Image
       run: |
         docker images
 
-    - name: Run Docker Containers
-      run: |
-        # Use the same tag that was used during build
+      - name: Run Docker Containers
+        run: |
         docker run -d -p 8081:80 $username/$image_name:${{ needs.Build.outputs.app_version }}
 
-    - name: Send email notification
-      uses: dawidd6/action-send-mail@v3
-      with:
-        server_address: smtp.gmail.com
-        server_port: 465
-        secure: true
-        username: oladapper@gmail.com
-        password: ${{ secrets.EMAIL_PASSWORD }}
-        subject: "Docker Image Deployed from Artifact"
-        to: "oladapolawal12@yahoo.com"
-        from: "Mr David Agba DevOps"
-        body: |
-          Hello,
-          The latest version of the Docker image (version: ${{ needs.Build.outputs.app_version }}) has been deployed from the artifact.
+      - name: Send email notification
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 465
+          secure: true
+          username: oladapper@gmail.com
+          password: ${{ secrets.EMAIL_PASSWORD }}
+          subject: "Docker Image Deployed from Artifact"
+          to: "oladapolawal12@yahoo.com"
+          from: "Mr David Agba DevOps"
+          body: |
+            Hello,
+            The latest version of the Docker image (version: ${{ needs.Build.outputs.app_version }}) has been deployed from the artifact.
